apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-kube-apiserver
  name: trusted-ca-bundle
  annotations:
    "openshift.io/owning-component": "Networking / cluster-network-operator"
    "openshift.io/description": "CA used to recognize proxy servers.  By default this will contain standard root CAs on the cluster-network-operator pod."
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
