apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-apiserver-operator
  namespace: openshift-kube-apiserver-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    exclude.release.openshift.io/internal-openshift-hosted: "true"
spec:
  endpoints:
  - interval: 30s
    metricRelabelings:
    - action: drop
      regex: etcd_(debugging|disk|request|server).*
      sourceLabels:
      - __name__
    port: https
    scheme: https
    tlsConfig:
      serverName: metrics.openshift-kube-apiserver-operator.svc
  jobLabel: app
  scrapeClass: tls-client-certificate-auth
  selector:
    matchLabels:
      app: kube-apiserver-operator
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kube-apiserver-operator
  namespace: openshift-kube-apiserver-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    exclude.release.openshift.io/internal-openshift-hosted: "true"
spec:
  groups:
  - name: cluster-version
    rules:
    - alert: TechPreviewNoUpgrade
      annotations:
        summary: Cluster has enabled tech preview features that will prevent upgrades.
        description: >-
          Cluster has enabled Technology Preview features that cannot be undone and will prevent upgrades.
          The TechPreviewNoUpgrade feature set is not recommended on production clusters.
      expr: |
        cluster_feature_set{name=~"TechPreviewNoUpgrade|CustomNoUpgrade", namespace="openshift-kube-apiserver-operator"} == 0
      for: 10m
      labels:
        severity: warning
