# this matches what the installer uses to create the admin.kubeconfig.  We must always honor this as a client or the admin.kubeconfig will become invalid
apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-kubeconfig-client-ca
  namespace: openshift-config
  annotations:
    "openshift.io/owning-component": "kube-apiserver"
    "openshift.io/description": "CA for kube-apiserver to recognize the system:master created by the installer."
data:
  ca-bundle.crt: |
    {{ .Assets | load "admin-kubeconfig-ca-bundle.crt" | indent 4 }}
