apiVersion: v1
kind: Secret
metadata:
  name: kube-apiserver-to-kubelet-signer
  namespace: openshift-kube-apiserver-operator
  annotations:
    "auth.openshift.io/certificate-not-before": {{ .Assets | load "kube-apiserver-to-kubelet-signer.crt" | notBefore }}
    "auth.openshift.io/certificate-not-after": {{ .Assets | load "kube-apiserver-to-kubelet-signer.crt" | notAfter }}
    "auth.openshift.io/certificate-issuer": {{ .Assets | load "kube-apiserver-to-kubelet-signer.crt" | issuer }}
    "openshift.io/owning-component": "kube-apiserver"
    "openshift.io/description": "Signer for the kube-apiserver-to-kubelet-client so kubelets can recognize the kube-apiserver."
type: kubernetes.io/tls
data:
  tls.crt: {{ .Assets | load "kube-apiserver-to-kubelet-signer.crt" | base64 }}
  tls.key: {{ .Assets | load "kube-apiserver-to-kubelet-signer.key" | base64 }}
